Ext.define('module.qc.insp.inspreport.model.InspReportLister3',{ extend:'Axt.data.Model',
	fields:
	[
		{	name: 'invc_numb'		, type: 'string' },
		{	name: 'line_seqn'		, type: 'float' },
		{	name: 'bzpl_idcd'		, type: 'string' },
		{	name: 'invc_date'		, type: 'string', defaultValue : Ext.Date.format(new Date(),'Ymd'), convert : Ext.util.Format.strToDate, serialize: Ext.util.Format.dateToStr },//INVOICE일자
		{	name: 'insp_dvcd'		, type: 'string' },
		{	name: 'cstm_idcd'		, type: 'string' },
		{	name: 'dlvy_idcd'		, type: 'string' },
		{	name: 'dlvy_seqn'		, type: 'float' },
		{	name: 'cnfm_dept_idcd'	, type: 'string' },
		{	name: 'cnfm_drtr_idcd'	, type: 'string' },
		{	name: 'pdsd_numb'		, type: 'string' },
		{	name: 'wkod_numb'		, type: 'string' },
		{	name: 'acpt_numb'		, type: 'string' },
		{	name: 'acpt_amnd_degr'	, type: 'string' },
		{	name: 'acpt_seqn'		, type: 'float' },
		{	name: 'item_idcd'		, type: 'string' },
		{	name: 'unit_idcd'		, type: 'string' },
		{	name: 'wkct_idcd'		, type: 'string' },
		{	name: 'wkct_item_idcd'	, type: 'string' },
		{	name: 'work_indn_qntt'	, type: 'float' },
		{	name: 'prod_qntt'		, type: 'float' },
		{	name: 'pass_qntt'		, type: 'float' },
		{	name: 'insp_mthd_dvcd'	, type: 'string' },
		{	name: 'insp_qntt'		, type: 'float' },
		{	name: 'smor_pass_qntt'	, type: 'float' },
		{	name: 'smor_poor_qntt'	, type: 'float' },
		{	name: 'judt_dvcd'		, type: 'string' },
		{	name: 'pass_yorn'		, type: 'string' },
		{	name: 'stnd_unit'		, type: 'string' },
		{	name: 'lott_numb'		, type: 'string' },
		{	name: 'sral_strt_numb'	, type: 'string' },
		{	name: 'work_dvcd'		, type: 'string' },
		{	name: 'insp_scre_numb'	, type: 'string' },
		{	name: 'smpl_numb'		, type: 'string' },
		{	name: 'istt_yorn'		, type: 'string' },
		{	name: 'cstm_name'		, type: 'string' },
		{	name: 'item_name'		, type: 'string' },
		{	name: 'item_spec'		, type: 'string' },
		{	name: 'unit_name'		, type: 'string' },
		{	name: 'wkct_name'		, type: 'string' },
		{	name: 'dept_name'		, type: 'string' },
		{	name: 'user_name'		, type: 'string' },
		{	name: 'istt_date'		, type: 'string' , defaultValue : Ext.Date.format(new Date(),'Ymd'), convert : Ext.util.Format.strToDate, serialize: Ext.util.Format.dateToStr }, // 입고일자
		{	name: 'prod_istt_qntt'	, type: 'float'  },

		{	name: 'insp_sbsc_name'	, type: 'string' },	/* 검사항목명	*/

		{	name: 'remk_text'		, type: 'string' },
		{	name: 'memo'			, type: 'string' },
		{	name: 'uper_seqn'		, type: 'float'  },
		{	name: 'disp_seqn'		, type: 'float'  },
	]
});
