package com.sky.system.custom.iypkg.mtrl.purc.purccstmlist1;

import net.sky.http.dispatch.control.DefaultServiceHandler;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.sky.data.DataMessage;
import com.sky.data.SqlResultMap;
import com.sky.http.HttpRequestArgument;
import com.sky.listener.ParamToJson;
import com.sky.listener.SeqListenerService;


@Service("iypkg.PurcCstmList1Service")
public class PurcCstmList1Service extends DefaultServiceHandler {
	@Autowired
	SeqListenerService sequence ;

	public SqlResultMap getSearch(HttpRequestArgument arg, int page, int rows, String sort ) throws Exception {
		DataMessage data = arg.newStorage("POS");
		String dvcd = arg.getParamText("dvcd");

		data.param // 집계문  입력
			.total(" select  count(1) as maxsize  ")
		;
		if(dvcd.equals("1")){
			data.param
				.query("select *																										")
				.where("from ( 																											")
				.where("with cte as ( 																									")
				.where("     select a.invc_numb       , a.line_seqn       , b.invc_date       , b.cstm_idcd								")
				.where("          , c.cstm_name       , a.item_idcd as fabc_idcd              , bm.fabc_name							")
				.where("          , f.fabc_code       , f.ppln_dvcd       , json_value(a.json_data, '$**.item_fxqt') as item_fxqt		")
				.where("          , bm.fdat_spec      , a.istt_qntt       , json_value(a.json_data, '$**.subt_qntt') as subt_qntt		")
				.where("          , json_value(p.json_data, '$**.mxm2_pric') as mxm2_pric												")
				.where("          , json_value(p.json_data, '$**.pqty_pric') as pqty_pric												")
				.where("          , a.istt_amnt       , a.istt_vatx       , a.ttsm_amnt       , b.invc_date as crt_date					")
				.where("          , ifnull(t.ttsm_amnt,0) as txbl_ttsm    , a.ttsm_amnt - ifnull(t.ttsm_amnt,0) as unpay				")
				.where("     from purc_istt_item a																						")
				.where("      left outer join purc_istt_mast b   on a.invc_numb = b.invc_numb											")
				.where("      left outer join cstm_mast      c   on b.cstm_idcd = c.cstm_idcd											")
				.where("      left outer join fabc_mast      f   on a.item_idcd = f.fabc_idcd											")
				.where("      left outer join purc_ordr_item p   on a.orig_invc_numb = p.invc_numb and a.orig_seqn = p.line_seqn		")
				.where("      left outer join purc_ordr_mast pm  on p.invc_numb = pm.invc_numb											")
				.where("      left outer join boxx_acpt_bom  bm  on p.orig_invc_numb = bm.invc_numb and p.orig_seqn = bm.line_seqn		")
				.where("      left outer join txbl_item      t   on a.invc_numb = t.orig_invc_numb and a.line_seqn = t.orig_invc_seqn	")
				.where("     where 1=1																									")
				.where("     and    json_value(pm.json_data, '$**.offr_path_dvcd') = 1													")
				.where("     and    a.find_name  like %:find_name%			" , arg.getParamText("find_name"))
				.where("     and    c.cstm_code >= :cstm_code				" , arg.getParameter("cstm_code"))
				.where("     and    c.cstm_code <= :cstm_code2				" , arg.getParameter("cstm_code2"))
				.where("     and    b.invc_date  >= :fr_invc_date			" , arg.getParamText("invc1_date"))
				.where("     and    b.invc_date  <= :to_invc_date			" , arg.getParamText("invc2_date"))
				.where("     and    a.line_stat   = :line_stat				" , arg.getParamText("line_stat"))
				.where(")																												")
			;

			data.param
				.where(" select  a.invc_numb															")
				.where("       , a.line_seqn															")
				.where("       , a.invc_date															")
				.where("       , a.cstm_idcd															")
				.where("       , a.cstm_name															")
				.where("       , a.fabc_idcd															")
				.where("       , a.fabc_name															")
				.where("       , a.fabc_code															")
				.where("       , a.ppln_dvcd															")
				.where("       , a.item_fxqt															")
				.where("       , a.fdat_spec															")
				.where("       , a.istt_qntt															")
				.where("       , a.subt_qntt															")
				.where("       , a.mxm2_pric															")
				.where("       , a.pqty_pric															")
				.where("       , a.istt_amnt															")
				.where("       , a.istt_vatx															")
				.where("       , a.ttsm_amnt															")
				.where("       , a.txbl_ttsm															")
				.where("       , a.unpay																")
				.where("       , a.crt_date																")
				.where("       , 1 as rnum																")
				.where("       , count(*) as cnt														")
				.where(" from cte a																		")
				.where(" group by a.invc_date, a.invc_numb, a.line_seqn, a.fabc_idcd, a.cstm_idcd		")
			;
			if(arg.getParamText("chk" ).contains("1")){			//소계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , null as invc_date														")
					.where("       , a.cstm_idcd															")
					.where("       , concat(a.cstm_name, ' 계') as cstm_name									")
					.where("       , a.fabc_idcd															")
					.where("       , null as fabc_name														")
					.where("       , null as fabc_code														")
					.where("       , null as ppln_dvcd														")
					.where("       , null as item_fxqt														")
					.where("       , null as fdat_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as mxm2_pric														")
					.where("       , null as pqty_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , sum(a.txbl_ttsm) as txbl_ttsm											")
					.where("       , sum(a.unpay) as unpay													")
					.where("       , a.invc_date as crt_date												")
					.where("       , 2 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date, a.cstm_idcd												")
					.where(" having cnt > 1																	")
				;
			}
			if(arg.getParamText("chk" ).contains("2")){			//일계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , a.invc_date															")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '일계' as cstm_name														")
					.where("       , null as fabc_idcd														")
					.where("       , null as fabc_name														")
					.where("       , null as fabc_code														")
					.where("       , null as ppln_dvcd														")
					.where("       , null as item_fxqt														")
					.where("       , null as fdat_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as mxm2_pric														")
					.where("       , null as pqty_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , sum(a.txbl_ttsm) as txbl_ttsm											")
					.where("       , sum(a.unpay) as unpay													")
					.where("       , a.invc_date as crt_date												")
					.where("       , 3 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date															")
				;
			}
			if(arg.getParamText("chk" ).contains("3")){			//월계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , substr(a.invc_date, 1, 6) as invc_date 								")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '월계' as cstm_name														")
					.where("       , null as fabc_idcd														")
					.where("       , null as fabc_name														")
					.where("       , null as fabc_code														")
					.where("       , null as ppln_dvcd														")
					.where("       , null as item_fxqt														")
					.where("       , null as fdat_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as mxm2_pric														")
					.where("       , null as pqty_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , sum(a.txbl_ttsm) as txbl_ttsm											")
					.where("       , sum(a.unpay) as unpay													")
					.where("       , concat(substr(a.invc_date,1,6),'99') as crt_date						")
					.where("       , 4 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by substr(a.invc_date, 1, 6)												")
				;
			}
			if(arg.getParamText("chk" ).contains("4")){			//합계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , '합계' as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , null as cstm_name														")
					.where("       , null as fabc_idcd														")
					.where("       , null as fabc_name														")
					.where("       , null as fabc_code														")
					.where("       , null as ppln_dvcd														")
					.where("       , null as item_fxqt														")
					.where("       , null as fdat_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as mxm2_pric														")
					.where("       , null as pqty_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , sum(a.txbl_ttsm) as txbl_ttsm											")
					.where("       , sum(a.unpay) as unpay													")
					.where("       , '99999999' as crt_date													")
					.where("       , 5 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by '99999999'															")
				;
			}
			data.param
				.where(" ORDER BY crt_date, cstm_idcd, rnum													")
				.where(") a																					")
			;
		}else if(dvcd.equals("2")){
			data.param
				.query("select *																										")
				.where("from ( 																											")
				.where("with cte as ( 																									")
				.where("     select a.invc_numb       , a.line_seqn       , pm.invc_date      , pm.cstm_idcd							")
				.where("          , c.cstm_name       , a.item_idcd as fabc_idcd              , f.fabc_name								")
				.where("          , f.fabc_code       , f.ppln_dvcd       , json_value(pi.json_data, '$**.item_fxqt') as item_fxqt		")
				.where("          , ba.fdat_spec      , sum(a.qntt) as istt_qntt														")
				.where("          , json_value(pi.json_data, '$**.subt_qntt') as subt_qntt												")
				.where("          , json_value(po.json_data, '$**.mxm2_pric') as mxm2_pric												")
				.where("          , json_value(po.json_data, '$**.pqty_pric') as pqty_pric												")
				.where("          , sum(a.sply_amnt) as istt_amnt         , sum(a.vatx_amnt) as istt_vatx								")
				.where("          , sum(a.ttsm_amnt) as ttsm_amnt         , pm.invc_date as crt_date									")
				.where("          , 1 as rnum         , count(*) as cnt																	")
				.where("     from txbl_item a																							")
				.where("      left outer join txbl_mast      b  on a.invc_numb = b.invc_numb											")
				.where("      left outer join purc_istt_item pi on a.orig_invc_numb = pi.invc_numb and a.orig_invc_seqn = pi.line_seqn	")
				.where("      left outer join purc_istt_mast pm on pi.invc_numb = pm.invc_numb											")
				.where("      left outer join purc_ordr_item po on pi.orig_invc_numb = po.invc_numb and pi.orig_seqn = po.line_seqn		")
				.where("      left outer join cstm_mast      c  on pi.cstm_idcd = c.cstm_idcd											")
				.where("      left outer join fabc_mast      f  on a.item_idcd = f.fabc_idcd											")
				.where("      left outer join boxx_acpt_bom  ba on json_value(pi.json_data, '$**.acpt_numb') = ba.invc_numb				")
				.where("     where 1=1																									")
				.where("     and    b.puch_sale_dvcd = 1																				")
				.where("     and    b.txbl_path_dvcd = 11																				")
				.where("     and    a.find_name  like %:find_name%			" , arg.getParamText("find_name" ))
				.where("     and    pm.cstm_idcd >= :cstm_idcd1				" , arg.getParamText("cstm_idcd"))
				.where("     and    pm.cstm_idcd <= :cstm_idcd2				" , arg.getParamText("cstm_idcd2"))
				.where("     and    pm.invc_date >= :invc1_date				" , arg.getParamText("fr_dt"))
				.where("     and    pm.invc_date <= :invc2_date				" , arg.getParamText("to_dt"))
				.where("     and    a.line_stat   = :line_stat				" , arg.getParamText("line_stat" ))
				.where("     group by a.orig_invc_numb, a.orig_invc_seqn																")
				.where(")																												")
			;

			data.param
				.where(" select  a.invc_numb															")
				.where("       , a.line_seqn															")
				.where("       , a.invc_date															")
				.where("       , a.cstm_idcd															")
				.where("       , a.cstm_name															")
				.where("       , a.fabc_idcd															")
				.where("       , a.fabc_name															")
				.where("       , a.fabc_code															")
				.where("       , a.ppln_dvcd															")
				.where("       , a.item_fxqt															")
				.where("       , a.fdat_spec															")
				.where("       , a.istt_qntt															")
				.where("       , a.subt_qntt															")
				.where("       , a.mxm2_pric															")
				.where("       , a.pqty_pric															")
				.where("       , a.istt_amnt															")
				.where("       , a.istt_vatx															")
				.where("       , a.ttsm_amnt															")
				.where("       , a.crt_date																")
				.where("       , 1 as rnum																")
				.where("       , count(*) as cnt														")
				.where(" from cte a																		")
				.where(" group by a.invc_date, a.invc_numb, a.line_seqn, a.fabc_idcd, a.cstm_idcd		")
			;
			if(arg.getParamText("chk" ).contains("1")){			//소계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , null as invc_date														")
					.where("       , a.cstm_idcd															")
					.where("       , '소계' as cstm_name														")
					.where("       , a.fabc_idcd															")
					.where("       , null as fabc_name														")
					.where("       , null as fabc_code														")
					.where("       , null as ppln_dvcd														")
					.where("       , null as item_fxqt														")
					.where("       , null as fdat_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as mxm2_pric														")
					.where("       , null as pqty_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , a.invc_date as crt_date												")
					.where("       , 2 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date, a.cstm_idcd												")
					.where(" having cnt > 1																	")
				;
			}
			if(arg.getParamText("chk" ).contains("2")){			//일계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , null as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '일계' as cstm_name														")
					.where("       , null as fabc_idcd														")
					.where("       , null as fabc_name														")
					.where("       , null as fabc_code														")
					.where("       , null as ppln_dvcd														")
					.where("       , null as item_fxqt														")
					.where("       , null as fdat_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as mxm2_pric														")
					.where("       , null as pqty_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , a.invc_date as crt_date												")
					.where("       , 3 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date															")
				;
			}
			if(arg.getParamText("chk" ).contains("3")){			//월계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , substr(a.invc_date, 1, 6) as invc_date 								")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '월계' as cstm_name														")
					.where("       , null as fabc_idcd														")
					.where("       , null as fabc_name														")
					.where("       , null as fabc_code														")
					.where("       , null as ppln_dvcd														")
					.where("       , null as item_fxqt														")
					.where("       , null as fdat_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as mxm2_pric														")
					.where("       , null as pqty_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , concat(substr(a.invc_date,1,6),'99') as crt_date						")
					.where("       , 4 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by substr(a.invc_date, 1, 6)												")
				;
			}
			if(arg.getParamText("chk" ).contains("4")){			//합계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , '합계' as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , null as cstm_name														")
					.where("       , null as fabc_idcd														")
					.where("       , null as fabc_name														")
					.where("       , null as fabc_code														")
					.where("       , null as ppln_dvcd														")
					.where("       , null as item_fxqt														")
					.where("       , null as fdat_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as mxm2_pric														")
					.where("       , null as pqty_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , '99999999' as crt_date													")
					.where("       , 5 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by '99999999'															")
				;
			}
			data.param
				.where(" ORDER BY crt_date, cstm_idcd, rnum													")
				.where(") a																					")
			;
		}

		if (page == 0 && rows == 0){
			return data.selectForMap(sort) ;
		} else {
			return data.selectForMap(page, rows, (page==1), sort );
		}
	}


	public SqlResultMap getSearch2(HttpRequestArgument arg, int page, int rows, String sort ) throws Exception {
		DataMessage data = arg.newStorage("POS");
		String dvcd = arg.getParamText("dvcd");

		data.param // 집계문  입력
			.total(" select  count(1) as maxsize  ")
		;
		if(dvcd.equals("1")){
			data.param
				.query("select *																										")
				.where("from ( 																											")
				.where("with cte as ( 																									")
				.where("     select a.invc_numb       , b.invc_date       , b.cstm_idcd       , c.cstm_name								")
				.where("          , w.wkct_name       , bp.wkun_dvcd      , a.istt_qntt       , u.unit_name								")
				.where("          , a.istt_pric       , a.istt_amnt       , a.istt_vatx       , a.ttsm_amnt								")
				.where("          , ba.prod_name      , pr.prod_spec      , b.invc_date as crt_date										")
				.where("          , bp.wkct_idcd																						")
				.where("     from purc_istt_item a																						")
				.where("      left outer join purc_istt_mast b   on a.invc_numb = b.invc_numb											")
				.where("      left outer join cstm_mast      c   on b.cstm_idcd = c.cstm_idcd											")
				.where("      left outer join purc_ordr_item p   on a.orig_invc_numb = p.invc_numb and a.orig_seqn = p.line_seqn		")
				.where("      left outer join purc_ordr_mast pm  on p.invc_numb = pm.invc_numb											")
				.where("      left outer join boxx_acpt      ba  on p.orig_invc_numb = ba.invc_numb										")
				.where("      left outer join product_mast   pr  on ba.prod_idcd = pr.prod_idcd											")
				.where("      left outer join boxx_acpt_bop  bp  on p.orig_invc_numb = bp.invc_numb and p.orig_seqn = bp.line_seqn		")
				.where("      left outer join unit_mast      u   on bp.qntt_unit_idcd = u.unit_idcd										")
				.where("      left outer join wkct_mast      w   on bp.wkct_idcd=w.wkct_idcd											")
				.where("     where 1=1																									")
				.where("     and    pm.offr_dvcd = '3000'																				")
				.where("     and    a.find_name  like %:find_name%			" , arg.getParamText("find_name"))
				.where("     and    c.cstm_code >= :cstm_code				" , arg.getParameter("cstm_code"))
				.where("     and    c.cstm_code <= :cstm_code2				" , arg.getParameter("cstm_code2"))
				.where("     and    b.invc_date  >= :fr_invc_date			" , arg.getParamText("invc1_date"))
				.where("     and    b.invc_date  <= :to_invc_date			" , arg.getParamText("invc2_date"))
				.where("     and    a.line_stat   = :line_stat				" , arg.getParamText("line_stat"))
				.where(")																												")
			;

			data.param
				.where(" select  a.invc_numb															")
				.where("       , a.invc_date															")
				.where("       , a.cstm_idcd															")
				.where("       , a.cstm_name															")
				.where("       , a.wkct_idcd															")
				.where("       , a.wkct_name															")
				.where("       , a.wkun_dvcd															")
				.where("       , a.unit_name															")
				.where("       , a.istt_qntt															")
				.where("       , a.istt_pric															")
				.where("       , a.istt_amnt															")
				.where("       , a.istt_vatx															")
				.where("       , a.ttsm_amnt															")
				.where("       , a.prod_name															")
				.where("       , a.prod_spec															")
				.where("       , a.crt_date																")
				.where("       , 1 as rnum																")
				.where("       , count(*) as cnt														")
				.where(" from cte a																		")
				.where(" group by a.invc_date, a.cstm_idcd, a.invc_numb, a.wkct_idcd					")
			;
			if(arg.getParamText("chk" ).contains("1")){			//소계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as invc_date														")
					.where("       , a.cstm_idcd															")
					.where("       , concat(a.cstm_name, ' 계') as cstm_name									")
					.where("       , null as wkct_idcd														")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , a.invc_date as crt_date												")
					.where("       , 2 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date, a.cstm_idcd									")
//					.where(" having cnt > 1																	")
				;
			}
			if(arg.getParamText("chk" ).contains("2")){			//일계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , a.invc_date															")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '일계' as cstm_name														")
					.where("       , null as wkct_idcd														")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , a.invc_date as crt_date												")
					.where("       , 3 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date															")
				;
			}
			if(arg.getParamText("chk" ).contains("3")){			//월계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , substr(a.invc_date, 1, 6) as invc_date 								")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '월계' as cstm_name														")
					.where("       , null as wkct_idcd														")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , concat(substr(a.invc_date,1,6),'99') as crt_date						")
					.where("       , 4 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by substr(a.invc_date, 1, 6)												")
				;
			}
			if(arg.getParamText("chk" ).contains("4")){			//합계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , '합계' as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , null as cstm_name														")
					.where("       , null as wkct_idcd														")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , '99999999' as crt_date													")
					.where("       , 5 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by '99999999'															")
				;
			}
			data.param
				.where(" ORDER BY crt_date, cstm_idcd, rnum													")
				.where(") a																					")
			;
		}else if(dvcd.equals("2")){
			data.param
				.query("select *																										")
				.where("from ( 																											")
				.where("with cte as ( 																									")
				.where("     select a.invc_numb       , a.line_seqn       , pm.invc_date      , pm.cstm_idcd							")
				.where("          , c.cstm_name       , a.item_idcd       , p.prod_name       , p.prod_spec								")
				.where("          , bp.wkct_idcd      , w.wkct_name       , bp.wkun_dvcd      , u.unit_name								")
				.where("          , ifnull(sum(json_value(pi.json_data, '$**.subt_qntt')),0) as subt_qntt								")
				.where("          , sum(a.sply_amnt) as istt_amnt         , sum(a.vatx_amnt) as istt_vatx								")
				.where("          , sum(a.ttsm_amnt) as ttsm_amnt         , pm.invc_date as crt_date									")
				.where("          , sum(a.qntt) as istt_qntt              , a.pric as istt_pric											")
				.where("     from txbl_item a																							")
				.where("      left outer join txbl_mast      b  on a.invc_numb = b.invc_numb											")
				.where("      left outer join purc_istt_item pi on a.orig_invc_numb = pi.invc_numb and a.orig_invc_seqn = pi.line_seqn	")
				.where("      left outer join purc_istt_mast pm on pi.invc_numb = pm.invc_numb											")
				.where("      left outer join purc_ordr_item po on pi.orig_invc_numb = po.invc_numb and pi.orig_seqn = po.line_seqn		")
				.where("      left outer join cstm_mast      c  on pi.cstm_idcd = c.cstm_idcd											")
				.where("      left outer join product_mast   p  on a.item_idcd = p.prod_idcd											")
				.where("      left outer join boxx_acpt_bop  bp on po.orig_invc_numb = bp.invc_numb and po.orig_seqn = bp.line_seqn		")
				.where("      left outer join wkct_mast      w  on bp.wkct_idcd = w.wkct_idcd											")
				.where("      left outer join unit_mast      u  on bp.qntt_unit_idcd = u.unit_idcd										")
				.where("     where 1=1																									")
				.where("     and    b.puch_sale_dvcd = 1																				")
				.where("     and    b.txbl_path_dvcd = 15																				")
				.where("     and    a.find_name  like %:find_name%			" , arg.getParamText("find_name" ))
				.where("     and    b.cstm_idcd >= :cstm_idcd1				" , arg.getParamText("cstm_idcd"))
				.where("     and    b.cstm_idcd <= :cstm_idcd2				" , arg.getParamText("cstm_idcd2"))
				.where("     and    b.publ_date >= :invc1_date				" , arg.getParamText("invc1_date"))
				.where("     and    b.publ_date <= :invc2_date				" , arg.getParamText("invc2_date"))
				.where("     and    a.line_stat   = :line_stat				" , arg.getParamText("line_stat" ))
				.where("     group by a.orig_invc_numb, a.orig_invc_seqn																")
				.where(")																												")
			;

			data.param
				.where(" select  a.invc_numb															")
				.where("       , a.invc_date															")
				.where("       , a.cstm_idcd															")
				.where("       , a.cstm_name															")
				.where("       , a.item_idcd															")
				.where("       , a.prod_name															")
				.where("       , a.prod_spec															")
				.where("       , a.istt_qntt															")
				.where("       , a.subt_qntt															")
				.where("       , a.istt_pric															")
				.where("       , a.istt_amnt															")
				.where("       , a.istt_vatx															")
				.where("       , a.ttsm_amnt															")
				.where("       , a.wkct_name															")
				.where("       , a.wkun_dvcd															")
				.where("       , a.unit_name															")
				.where("       , a.crt_date																")
				.where("       , 1 as rnum																")
				.where("       , count(*) as cnt														")
				.where(" from cte a																		")
				.where(" group by a.invc_date, a.cstm_idcd, a.invc_numb, a.wkct_idcd					")
			;
			if(arg.getParamText("chk" ).contains("1")){			//소계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as invc_date														")
					.where("       , a.cstm_idcd															")
					.where("       , concat(a.cstm_name,' 계') as cstm_name									")
					.where("       , null as item_idcd														")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , a.invc_date as crt_date												")
					.where("       , 2 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date, a.cstm_idcd												")
					.where(" having cnt > 1																	")
				;
			}
			if(arg.getParamText("chk" ).contains("2")){			//일계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , a.invc_date															")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '일계' as cstm_name														")
					.where("       , null as item_idcd														")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , a.invc_date as crt_date												")
					.where("       , 3 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date															")
				;
			}
			if(arg.getParamText("chk" ).contains("3")){			//월계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , substr(a.invc_date, 1, 6) as invc_date 								")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '월계' as cstm_name														")
					.where("       , null as item_idcd														")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , concat(substr(a.invc_date,1,6),'99') as crt_date						")
					.where("       , 4 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by substr(a.invc_date, 1, 6)												")
				;
			}
			if(arg.getParamText("chk" ).contains("4")){			//합계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , '합계' as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , null as cstm_name														")
					.where("       , null as item_idcd														")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , '99999999' as crt_date													")
					.where("       , 5 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by '99999999'															")
				;
			}
			data.param
				.where(" ORDER BY crt_date, cstm_idcd, rnum													")
				.where(") a																					")
			;
		}

		if (page == 0 && rows == 0){
			return data.selectForMap(sort) ;
		} else {
			return data.selectForMap(page, rows, (page==1), sort );
		}
	}
	public SqlResultMap getSearch3(HttpRequestArgument arg, int page, int rows, String sort ) throws Exception {
		DataMessage data = arg.newStorage("POS");
		String dvcd = arg.getParamText("dvcd");

		data.param // 집계문  입력
			.total(" select  count(1) as maxsize  ")
		;
		if(dvcd.equals("1")){
			data.param
				.query("select *																										")
				.where("from ( 																											")
				.where("with cte as ( 																									")
				.where("     select a.invc_numb       , b.invc_date       , b.cstm_idcd       , c.cstm_name								")
				.where("          , w.wkct_name       , bp.wkun_dvcd      , a.istt_qntt       , u.unit_name								")
				.where("          , a.istt_pric       , a.istt_amnt       , a.istt_vatx       , a.ttsm_amnt								")
				.where("          , ba.prod_name      , pr.prod_spec      , b.invc_date as crt_date										")
				.where("          , bp.wkct_idcd																						")
				.where("     from purc_istt_item a																						")
				.where("      left outer join purc_istt_mast b   on a.invc_numb = b.invc_numb											")
				.where("      left outer join cstm_mast      c   on b.cstm_idcd = c.cstm_idcd											")
				.where("      left outer join purc_ordr_item p   on a.orig_invc_numb = p.invc_numb and a.orig_seqn = p.line_seqn		")
				.where("      left outer join purc_ordr_mast pm  on p.invc_numb = pm.invc_numb											")
				.where("      left outer join boxx_acpt      ba  on p.orig_invc_numb = ba.invc_numb										")
				.where("      left outer join product_mast   pr  on ba.prod_idcd = pr.prod_idcd											")
				.where("      left outer join boxx_acpt_bop  bp  on p.orig_invc_numb = bp.invc_numb and p.orig_seqn = bp.line_seqn		")
				.where("      left outer join unit_mast      u   on bp.qntt_unit_idcd = u.unit_idcd										")
				.where("      left outer join wkct_mast      w   on bp.wkct_idcd=w.wkct_idcd											")
				.where("     where 1=1																									")
				.where("     and    ba.acpt_dvcd = '4000'																				")
				.where("     and    a.find_name  like %:find_name%			" , arg.getParamText("find_name"))
				.where("     and    c.cstm_code >= :cstm_code				" , arg.getParameter("cstm_code"))
				.where("     and    c.cstm_code <= :cstm_code2				" , arg.getParameter("cstm_code2"))
				.where("     and    b.invc_date  >= :fr_invc_date			" , arg.getParamText("invc1_date"))
				.where("     and    b.invc_date  <= :to_invc_date			" , arg.getParamText("invc2_date"))
				.where("     and    a.line_stat   = :line_stat				" , arg.getParamText("line_stat"))
				.where(")																												")
			;

			data.param
				.where(" select  a.invc_numb															")
				.where("       , a.invc_date															")
				.where("       , a.cstm_idcd															")
				.where("       , a.cstm_name															")
				.where("       , a.wkct_idcd															")
				.where("       , a.wkct_name															")
				.where("       , a.wkun_dvcd															")
				.where("       , a.unit_name															")
				.where("       , a.istt_qntt															")
				.where("       , a.istt_pric															")
				.where("       , a.istt_amnt															")
				.where("       , a.istt_vatx															")
				.where("       , a.ttsm_amnt															")
				.where("       , a.prod_name															")
				.where("       , a.prod_spec															")
				.where("       , a.crt_date																")
				.where("       , 1 as rnum																")
				.where("       , count(*) as cnt														")
				.where(" from cte a																		")
				.where(" group by a.invc_date, a.cstm_idcd, a.invc_numb, a.wkct_idcd					")
			;
			if(arg.getParamText("chk" ).contains("1")){			//소계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as invc_date														")
					.where("       , a.cstm_idcd															")
					.where("       , concat(a.cstm_name, ' 계') as cstm_name									")
					.where("       , null as wkct_idcd														")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , a.invc_date as crt_date												")
					.where("       , 2 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date, a.cstm_idcd									")
//					.where(" having cnt > 1																	")
				;
			}
			if(arg.getParamText("chk" ).contains("2")){			//일계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , a.invc_date															")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '일계' as cstm_name														")
					.where("       , null as wkct_idcd														")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , a.invc_date as crt_date												")
					.where("       , 3 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date															")
				;
			}
			if(arg.getParamText("chk" ).contains("3")){			//월계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , substr(a.invc_date, 1, 6) as invc_date 								")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '월계' as cstm_name														")
					.where("       , null as wkct_idcd														")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , concat(substr(a.invc_date,1,6),'99') as crt_date						")
					.where("       , 4 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by substr(a.invc_date, 1, 6)												")
				;
			}
			if(arg.getParamText("chk" ).contains("4")){			//합계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , '합계' as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , null as cstm_name														")
					.where("       , null as wkct_idcd														")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , '99999999' as crt_date													")
					.where("       , 5 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by '99999999'															")
				;
			}
			data.param
				.where(" ORDER BY crt_date, cstm_idcd, rnum													")
				.where(") a																					")
			;
		}else if(dvcd.equals("2")){
			data.param
				.query("select *																										")
				.where("from ( 																											")
				.where("with cte as ( 																									")
				.where("     select a.invc_numb       , a.line_seqn       , pm.invc_date      , pm.cstm_idcd							")
				.where("          , c.cstm_name       , a.item_idcd       , p.prod_name       , p.prod_spec								")
				.where("          , bp.wkct_idcd      , w.wkct_name       , bp.wkun_dvcd      , u.unit_name								")
				.where("          , ifnull(sum(json_value(pi.json_data, '$**.subt_qntt')),0) as subt_qntt								")
				.where("          , sum(a.sply_amnt) as istt_amnt         , sum(a.vatx_amnt) as istt_vatx								")
				.where("          , sum(a.ttsm_amnt) as ttsm_amnt         , pm.invc_date as crt_date									")
				.where("          , sum(a.qntt) as istt_qntt              , a.pric as istt_pric											")
				.where("     from txbl_item a																							")
				.where("      left outer join txbl_mast      b  on a.invc_numb = b.invc_numb											")
				.where("      left outer join purc_istt_item pi on a.orig_invc_numb = pi.invc_numb and a.orig_invc_seqn = pi.line_seqn	")
				.where("      left outer join purc_istt_mast pm on pi.invc_numb = pm.invc_numb											")
				.where("      left outer join purc_ordr_item po on pi.orig_invc_numb = po.invc_numb and pi.orig_seqn = po.line_seqn		")
				.where("      left outer join cstm_mast      c  on pi.cstm_idcd = c.cstm_idcd											")
				.where("      left outer join product_mast   p  on a.item_idcd = p.prod_idcd											")
				.where("      left outer join boxx_acpt_bop  bp on po.orig_invc_numb = bp.invc_numb and po.orig_seqn = bp.line_seqn		")
				.where("      left outer join wkct_mast      w  on bp.wkct_idcd = w.wkct_idcd											")
				.where("      left outer join unit_mast      u  on bp.qntt_unit_idcd = u.unit_idcd										")
				.where("     where 1=1																									")
				.where("     and    b.puch_sale_dvcd = 1																				")
				.where("     and    b.txbl_path_dvcd = 15																				")
				.where("     and    a.find_name  like %:find_name%			" , arg.getParamText("find_name" ))
				.where("     and    b.cstm_idcd >= :cstm_idcd1				" , arg.getParamText("cstm_idcd"))
				.where("     and    b.cstm_idcd <= :cstm_idcd2				" , arg.getParamText("cstm_idcd2"))
				.where("     and    b.publ_date >= :invc1_date				" , arg.getParamText("invc1_date"))
				.where("     and    b.publ_date <= :invc2_date				" , arg.getParamText("invc2_date"))
				.where("     and    a.line_stat   = :line_stat				" , arg.getParamText("line_stat" ))
				.where("     group by a.orig_invc_numb, a.orig_invc_seqn																")
				.where(")																												")
			;

			data.param
				.where(" select  a.invc_numb															")
				.where("       , a.invc_date															")
				.where("       , a.cstm_idcd															")
				.where("       , a.cstm_name															")
				.where("       , a.item_idcd															")
				.where("       , a.prod_name															")
				.where("       , a.prod_spec															")
				.where("       , a.istt_qntt															")
				.where("       , a.subt_qntt															")
				.where("       , a.istt_pric															")
				.where("       , a.istt_amnt															")
				.where("       , a.istt_vatx															")
				.where("       , a.ttsm_amnt															")
				.where("       , a.wkct_name															")
				.where("       , a.wkun_dvcd															")
				.where("       , a.unit_name															")
				.where("       , a.crt_date																")
				.where("       , 1 as rnum																")
				.where("       , count(*) as cnt														")
				.where(" from cte a																		")
				.where(" group by a.invc_date, a.cstm_idcd, a.invc_numb, a.wkct_idcd					")
			;
			if(arg.getParamText("chk" ).contains("1")){			//소계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as invc_date														")
					.where("       , a.cstm_idcd															")
					.where("       , concat(a.cstm_name,' 계') as cstm_name									")
					.where("       , null as item_idcd														")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , a.invc_date as crt_date												")
					.where("       , 2 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date, a.cstm_idcd												")
					.where(" having cnt > 1																	")
				;
			}
			if(arg.getParamText("chk" ).contains("2")){			//일계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , a.invc_date															")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '일계' as cstm_name														")
					.where("       , null as item_idcd														")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , a.invc_date as crt_date												")
					.where("       , 3 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date															")
				;
			}
			if(arg.getParamText("chk" ).contains("3")){			//월계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , substr(a.invc_date, 1, 6) as invc_date 								")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '월계' as cstm_name														")
					.where("       , null as item_idcd														")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , concat(substr(a.invc_date,1,6),'99') as crt_date						")
					.where("       , 4 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by substr(a.invc_date, 1, 6)												")
				;
			}
			if(arg.getParamText("chk" ).contains("4")){			//합계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , '합계' as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , null as cstm_name														")
					.where("       , null as item_idcd														")
					.where("       , null as prod_name														")
					.where("       , null as prod_spec														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , sum(a.subt_qntt) as subt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , null as wkct_name														")
					.where("       , null as wkun_dvcd														")
					.where("       , null as unit_name														")
					.where("       , '99999999' as crt_date													")
					.where("       , 5 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by '99999999'															")
				;
			}
			data.param
				.where(" ORDER BY crt_date, cstm_idcd, rnum													")
				.where(") a																					")
			;
		}

		if (page == 0 && rows == 0){
			return data.selectForMap(sort) ;
		} else {
			return data.selectForMap(page, rows, (page==1), sort );
		}
	}

	public SqlResultMap getSearch4(HttpRequestArgument arg, int page, int rows, String sort ) throws Exception {
		DataMessage data = arg.newStorage("POS");
		String dvcd = arg.getParamText("dvcd");

		data.param // 집계문  입력
			.total(" select  count(1) as maxsize  ")
		;
		if(dvcd.equals("1")){
			data.param
				.query("select *																										")
				.where("from ( 																											")
				.where("with cte as ( 																									")
				.where("     select a.invc_numb       , a.line_seqn       , b.invc_date       , b.cstm_idcd								")
				.where("          , c.cstm_name       , a.item_idcd as asmt_idcd              , ifnull(i.asmt_name, p.item_name) as asmt_name")
				.where("          , i.asmt_code       , json_value(p.json_data , '$**.asmt_dvcd') as asmt_dvcd							")
				.where("          , p.unit_idcd       , u.unit_name       , a.istt_qntt       , a.istt_pric								")
				.where("          , i.asmt_spec       , a.istt_amnt       , a.istt_vatx       , a.ttsm_amnt								")
				.where("          , a.vatx_incl_yorn  , b.invc_date as crt_date															")
				.where("     from purc_istt_item a																						")
				.where("      left outer join purc_istt_mast b   on a.invc_numb = b.invc_numb											")
				.where("      left outer join cstm_mast      c   on b.cstm_idcd = c.cstm_idcd											")
				.where("      left outer join asmt_mast      i   on a.item_idcd = i.asmt_idcd											")
				.where("      left outer join purc_ordr_item p   on a.orig_invc_numb = p.invc_numb and a.orig_seqn = p.line_seqn		")
				.where("      left outer join purc_ordr_mast pm  on p.invc_numb = pm.invc_numb											")
				.where("      left outer join unit_mast      u   on p.unit_idcd = u.unit_idcd											")
				.where("     where 1=1																									")
				.where("     and    json_value(pm.json_data, '$**.offr_path_dvcd') = 2													")
				.where("     and    a.find_name  like %:find_name%			" , arg.getParamText("find_name" ))
				.where("     and    b.cstm_idcd  >= :cstm_idcd				" , arg.getParamText("cstm_idcd"))
				.where("     and    b.cstm_idcd  <= :cstm_idcd				" , arg.getParamText("cstm_idcd2"))
				.where("     and    b.invc_date  >= :fr_invc_date			" , arg.getParamText("invc1_date"))
				.where("     and    b.invc_date  <= :to_invc_date			" , arg.getParamText("invc2_date"))
				.where("     and    a.line_stat   = :line_stat				" , arg.getParamText("line_stat" ))
				.where(")																												")
			;

			data.param
				.where(" select  a.invc_numb															")
				.where("       , a.line_seqn															")
				.where("       , a.invc_date															")
				.where("       , a.cstm_idcd															")
				.where("       , a.cstm_name															")
				.where("       , a.asmt_idcd															")
				.where("       , a.asmt_name															")
				.where("       , a.asmt_code															")
				.where("       , a.asmt_dvcd															")
				.where("       , a.unit_idcd															")
				.where("       , a.unit_name															")
				.where("       , a.istt_qntt															")
				.where("       , a.istt_pric															")
				.where("       , a.asmt_spec															")
				.where("       , a.istt_amnt															")
				.where("       , a.istt_vatx															")
				.where("       , a.ttsm_amnt															")
				.where("       , a.crt_date																")
				.where("       , 1 as rnum																")
				.where("       , count(*) as cnt														")
				.where(" from cte a																		")
				.where(" group by a.invc_date, a.invc_numb, a.line_seqn, a.asmt_idcd, a.cstm_idcd		")
			;
			if(arg.getParamText("chk" ).contains("1")){			//소계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , null as invc_date														")
					.where("       , a.cstm_idcd															")
					.where("       , concat(a.cstm_name, ' 계') as cstm_name									")
					.where("       , null as asmt_idcd														")
					.where("       , null as asmt_name														")
					.where("       , null as asmt_code														")
					.where("       , null as asmt_dvcd														")
					.where("       , null as unit_idcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , null as asmt_spec														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , a.invc_date as crt_date												")
					.where("       , 2 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date, a.cstm_idcd												")
					.where(" having cnt > 1																	")
				;
			}
			if(arg.getParamText("chk" ).contains("2")){			//일계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , a.invc_date															")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '일계' as cstm_name														")
					.where("       , null as asmt_idcd														")
					.where("       , null as asmt_name														")
					.where("       , null as asmt_code														")
					.where("       , null as asmt_dvcd														")
					.where("       , null as unit_idcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , null as asmt_spec														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , a.invc_date as crt_date												")
					.where("       , 3 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date															")
				;
			}
			if(arg.getParamText("chk" ).contains("3")){			//월계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , substr(a.invc_date,1,6) as invc_date									")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '월계' as cstm_name														")
					.where("       , null as asmt_idcd														")
					.where("       , null as asmt_name														")
					.where("       , null as asmt_code														")
					.where("       , null as asmt_dvcd														")
					.where("       , null as unit_idcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , null as asmt_spec														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , concat(substr(a.invc_date,1,6),'99') as crt_date						")
					.where("       , 4 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by substr(a.invc_date,1,6)												")
				;
			}
			if(arg.getParamText("chk" ).contains("4")){			//합계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , '합계' as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , null as cstm_name														")
					.where("       , null as asmt_idcd														")
					.where("       , null as asmt_name														")
					.where("       , null as asmt_code														")
					.where("       , null as asmt_dvcd														")
					.where("       , null as unit_idcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , null as asmt_spec														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , '99999999' as crt_date													")
					.where("       , 5 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by '99999999'															")
				;
			}
			data.param
				.where(" ORDER BY crt_date, cstm_idcd, rnum													")
				.where(") a																					")
			;
		}else if(dvcd.equals("2")){
			data.param
				.query("select *																										")
				.where("from ( 																											")
				.where("with cte as ( 																									")
				.where("     select a.invc_numb       , a.line_seqn       , pm.invc_date      , pm.cstm_idcd							")
				.where("          , c.cstm_name       , a.item_idcd as asmt_idcd              , am.asmt_name							")
				.where("          , am.asmt_code      , am.asmt_dvcd      , am.asmt_spec      , am.unit_idcd							")
				.where("          , u.unit_name       , sum(a.qntt) as istt_qntt              , pi.istt_pric							")
				.where("          , sum(a.sply_amnt) as istt_amnt         , sum(a.vatx_amnt) as istt_vatx								")
				.where("          , sum(a.ttsm_amnt) as ttsm_amnt         , pm.invc_date as crt_date									")
				.where("          , 1 as rnum         , count(*) as cnt																	")
				.where("     from txbl_item a																							")
				.where("      left outer join txbl_mast      b  on a.invc_numb = b.invc_numb											")
				.where("      left outer join purc_istt_item pi on a.orig_invc_numb = pi.invc_numb and a.orig_invc_seqn = pi.line_seqn	")
				.where("      left outer join purc_istt_mast pm on pi.invc_numb = pm.invc_numb											")
				.where("      left outer join purc_ordr_item po on pi.orig_invc_numb = po.invc_numb and pi.orig_seqn = po.line_seqn		")
				.where("      left outer join cstm_mast      c  on pi.cstm_idcd = c.cstm_idcd											")
				.where("      left outer join asmt_mast      am on a.item_idcd = am.asmt_idcd											")
				.where("      left outer join unit_mast      u  on am.unit_idcd = u.unit_idcd											")
				.where("      left outer join boxx_acpt_bom  ba on json_value(pi.json_data, '$**.acpt_numb') = ba.invc_numb				")
				.where("     where 1=1																									")
				.where("     and    b.puch_sale_dvcd = 1																				")
				.where("     and    b.txbl_path_dvcd = 14																				")
				.where("     and    a.find_name  like %:find_name%			" , arg.getParamText("find_name" ))
				.where("     and    pm.cstm_idcd >= :cstm_idcd1				" , arg.getParamText("cstm_idcd"))
				.where("     and    pm.cstm_idcd <= :cstm_idcd2				" , arg.getParamText("cstm_idcd2"))
				.where("     and    pm.invc_date >= :invc1_date				" , arg.getParamText("fr_dt"))
				.where("     and    pm.invc_date <= :invc2_date				" , arg.getParamText("to_dt"))
				.where("     and    a.line_stat   = :line_stat				" , arg.getParamText("line_stat" ))
				.where("     group by a.orig_invc_numb, a.orig_invc_seqn																")
				.where(")																												")
			;

			data.param
				.where(" select  a.invc_numb															")
				.where("       , a.line_seqn															")
				.where("       , a.invc_date															")
				.where("       , a.cstm_idcd															")
				.where("       , a.cstm_name															")
				.where("       , a.asmt_idcd															")
				.where("       , a.asmt_name															")
				.where("       , a.asmt_code															")
				.where("       , a.asmt_dvcd															")
				.where("       , a.unit_idcd															")
				.where("       , a.unit_name															")
				.where("       , a.istt_qntt															")
				.where("       , a.istt_pric															")
				.where("       , a.asmt_spec															")
				.where("       , a.istt_amnt															")
				.where("       , a.istt_vatx															")
				.where("       , a.ttsm_amnt															")
				.where("       , a.crt_date																")
				.where("       , 1 as rnum																")
				.where("       , count(*) as cnt														")
				.where(" from cte a																		")
				.where(" group by a.invc_date, a.invc_numb, a.line_seqn, a.asmt_idcd, a.cstm_idcd		")
			;
			if(arg.getParamText("chk" ).contains("1")){			//소계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , null as invc_date														")
					.where("       , a.cstm_idcd															")
					.where("       , '소계' as cstm_name														")
					.where("       , null as asmt_idcd														")
					.where("       , null as asmt_name														")
					.where("       , null as asmt_code														")
					.where("       , null as asmt_dvcd														")
					.where("       , null as unit_idcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , null as asmt_spec														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , a.invc_date as crt_date												")
					.where("       , 2 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date, a.cstm_idcd												")
					.where(" having cnt > 1																	")
				;
			}
			if(arg.getParamText("chk" ).contains("2")){			//일계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , null as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '일계' as cstm_name														")
					.where("       , null as asmt_idcd														")
					.where("       , null as asmt_name														")
					.where("       , null as asmt_code														")
					.where("       , null as asmt_dvcd														")
					.where("       , null as unit_idcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , null as asmt_spec														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , a.invc_date as crt_date												")
					.where("       , 3 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by a.invc_date															")
				;
			}
			if(arg.getParamText("chk" ).contains("3")){			//월계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , substr(a.invc_date,1,6) as invc_date									")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , '월계' as cstm_name														")
					.where("       , null as asmt_idcd														")
					.where("       , null as asmt_name														")
					.where("       , null as asmt_code														")
					.where("       , null as asmt_dvcd														")
					.where("       , null as unit_idcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , null as asmt_spec														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , concat(substr(a.invc_date,1,6),'99') as crt_date						")
					.where("       , 4 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by substr(a.invc_date,1,6)												")
				;
			}
			if(arg.getParamText("chk" ).contains("4")){			//합계
				data.param
					.where(" union all																		")
					.where(" select  null as invc_numb														")
					.where("       , null as line_seqn														")
					.where("       , '합계' as invc_date														")
					.where("       , max(a.cstm_idcd) as cstm_idcd											")
					.where("       , null as cstm_name														")
					.where("       , null as asmt_idcd														")
					.where("       , null as asmt_name														")
					.where("       , null as asmt_code														")
					.where("       , null as asmt_dvcd														")
					.where("       , null as unit_idcd														")
					.where("       , null as unit_name														")
					.where("       , sum(a.istt_qntt) as istt_qntt											")
					.where("       , null as istt_pric														")
					.where("       , null as asmt_spec														")
					.where("       , sum(a.istt_amnt) as istt_amnt											")
					.where("       , sum(a.istt_vatx) as istt_vatx											")
					.where("       , sum(a.ttsm_amnt) as ttsm_amnt											")
					.where("       , '99999999' as crt_date													")
					.where("       , 5 as rnum																")
					.where("       , count(*) as cnt														")
					.where(" from cte a																		")
					.where(" group by '99999999'															")
				;
			}
			data.param
				.where(" ORDER BY crt_date, cstm_idcd, rnum													")
				.where(") a																					")
			;
		}

		if (page == 0 && rows == 0){
			return data.selectForMap(sort) ;
		} else {
			return data.selectForMap(page, rows, (page==1), sort );
		}
	}

}
