Ext.define('module.project.domainmanager.model.TableDetail',{ extend:'Axt.data.Model',
	fields: [
		{   name: 'tabl_idcd'     , type: 'string'
		},{ name: 'tabl_name'     , type: 'string'
		},{ name: 'fied_idcd'     , type: 'string'
		},{ name: 'fld_seq'    , type: 'float'
		},{ name: 'fied_name'   , type: 'string'
		},{ name: 'data_type'  , type: 'string'
		},{ name: 'data_len'   , type: 'string'
		},{ name: 'key_dvcd'     , type: 'string'
		},{ name: 'null_dvcd'    , type: 'string'
		},{ name: 'dflt_valu'   , type: 'string'
		},{ name: 'old_id'     , type: 'string'
		},{ name: 'prnt_gbcd'  , type: 'string'
		},{ name: 'prnt_txt'   , type: 'string'
		},{ name: 'ref_table'  , type: 'string'
		},{ name: 'inter_val'  , type: 'string'
		},{ name: 'dscrt'      , type: 'string'
		},{ name: 'w_nm_1'     , type: 'string'
		},{ name: 'w_id_1'     , type: 'string'
		},{ name: 'w_nm_2'     , type: 'string'
		},{ name: 'w_id_2'     , type: 'string'
		},{ name: 'w_nm_3'     , type: 'string'
		},{ name: 'w_id_3'     , type: 'string'
		},{ name: 'w_nm_4'     , type: 'string'
		},{ name: 'w_id_4'     , type: 'string'
		},{ name: 'w_nm_5'     , type: 'string'
		},{ name: 'w_id_5'     , type: 'string'
		},{ name: 'w_nm_6'     , type: 'string'
		},{ name: 'w_id_6'     , type: 'string'
		},{ name: 'old_nm'     , type: 'string'
		},{ name: 'prjt_dvsn'     , type: 'string', defaultValue: 'MAIN'
		},{	name: '_fld_id'    , type: 'string'	, mapping : 'fied_idcd'
		}
    ]
});
