Ext.define('lookup.popup.project.model.DomainPopup',{ extend:'Axt.data.Model',
    fields: [
     	{name: 'field_id'			, type: 'string'  },
     	{name: 'fied_name'			, type: 'string'  },
     	{name: 'data_type'			, type: 'string'  },
     	{name: 'data_len'			, type: 'float'  },
     	{name: 'w_nm_1'				, type: 'string'  },
     	{name: 'w_id_1'				, type: 'string'  },
     	{name: 'w_nm_2'				, type: 'string'  },
     	{name: 'w_id_2'				, type: 'string'  },
     	{name: 'w_nm_3'				, type: 'string'  },
     	{name: 'w_id_3'				, type: 'string'  },
     	{name: 'w_nm_4'				, type: 'string'  },
     	{name: 'w_id_4'				, type: 'string'  },
     	{name: 'w_nm_5'				, type: 'string'  },
     	{name: 'w_id_5'				, type: 'string'  },
     	{name: 'w_nm_6'				, type: 'string'  },
     	{name: 'w_id_6'				, type: 'string'  },
     	{name: 'old_id'				, type: 'string'  },
     	{name: 'old_nm'				, type: 'string'  },
     	{name: 'ref_table'			, type: 'string'  },
     	{name: 'inter_val'			, type: 'string'  },
    ]
});
