package com.sky.system.custom.sjflv.mtrl.isttcalc.dailypurclist2;

import net.sky.http.dispatch.control.DefaultServiceHandler;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.sky.data.DataMessage;
import com.sky.data.SqlResultMap;
import com.sky.http.HttpRequestArgument;
import com.sky.listener.ParamToJson;
import com.sky.listener.SeqListenerService;


@Service("sjung.DailyPurcList2Service")
public class DailyPurcList2Service extends DefaultServiceHandler {
	@Autowired
	SeqListenerService sequence ;

	public SqlResultMap getSearch(HttpRequestArgument arg, int page, int rows, String sort ) throws Exception {
		DataMessage data = arg.newStorage("POS");

		data.param // 집계문  입력
			.total(" select  count(1) as maxsize	")
		;
		data.param
	    .query("select x.*																										")
	    ;
		data.param
			.where("from (																										")
			.where("with cte as (																								")
			.where("   select a.invc_numb 																						")
			.where("   	    , case when json_value(b.json_data, '$.trns_date') is null then a.invc_date else json_value(b.json_data, '$.trns_date') end as invc_date")
			.where("        , a.cstm_idcd, c.cstm_name																			")
			.where("        , b.line_seqn, b.item_idcd, d.item_code, d.item_name, d.item_spec									")
			.where("        , b.istt_qntt as qntt, b.istt_pric as pric															")
			.where("        , b.istt_amnt as sply_amnt, b.istt_vatx as vatx_amnt, b.ttsm_amnt									")
			.where("        , i.user_memo																						")
			.where("        , case when json_value(b.json_data, '$.trns_date') is null then 1  else 2 end trns_type				")
			.where("     from purc_istt_mast a																					")
			.where("          left outer join purc_istt_item b on b.invc_numb = a.invc_numb										")
			.where("          left outer join cstm_mast c on c.cstm_idcd = a.cstm_idcd											")
			.where("          left outer join item_mast d on d.item_idcd = b.item_idcd 											")
			.where("          left outer join  purc_ordr_item i on b.orig_invc_numb = i.invc_numb and b.orig_seqn = i.line_seqn	")
			.where("          left outer join wrhs_mast e on e.wrhs_idcd = a.istt_wrhs_idcd 									")
			.where("    where 1 = 1																								")
			.where("      and ((json_value(b.json_data, '$.trns_date') is null ")
			.where("      and a.invc_date >= :invc_date11" 			, arg.getParamText("invc_date1"))
			.where("      and a.invc_date <= :invc_date12)"			, arg.getParamText("invc_date2"))
			.where("       or  (json_value(b.json_data, '$.trns_date') is not null ")
			.where("      and json_value(b.json_data, '$.trns_date') >= :invc_date13"	, arg.getParamText("invc_date1"))
			.where("      and json_value(b.json_data, '$.trns_date') <= :invc_date14))"	, arg.getParamText("invc_date2"))
			.where("      and a.cstm_idcd  = :cstm_idcd1"   		, arg.getParamText("cstm_idcd"))
			.where("      and a.istt_wrhs_idcd  = :istt_wrhs_idcd1" , arg.getParamText("istt_wrhs_idcd"))
			.where("      and d.acct_bacd  = :acct_bacd1"     		, arg.getParamText("acct_bacd"))
			.where("      and b.item_idcd  = :item_idcd1"			, arg.getParamText("item_idcd"))
			.where("      and a.find_name like %:find_name1%	"	, arg.getParameter("find_name"))
			.where("      and a.line_stat  < 2																					")
			.where("    union all																								")
			.where("   select a.invc_numb, a.invc_date, a.cstm_idcd, c.cstm_name												")
			.where("        , b.line_seqn, b.item_idcd, d.item_code, d.item_name, d.item_spec									")
			.where("        , b.rett_qntt * -1 as qntt     , b.istt_pric as pric												")
			.where("        , b.sply_amnt * -1 as sply_amnt, b.vatx_amnt * -1 as vatx_amnt, b.ttsm_amnt * -1 as ttsm_amnt		")
			.where("        , i.user_memo																						")
			.where("        , 3 as trns_type																					")
			.where("     from purc_rett_mast a																					")
			.where("          left outer join purc_rett_item b on b.invc_numb = a.invc_numb										")
			.where("          left outer join cstm_mast c on c.cstm_idcd = a.cstm_idcd											")
			.where("          left outer join item_mast d on d.item_idcd = b.item_idcd 											")
			.where("          left outer join purc_ordr_item i on b.purc_invc_numb = i.invc_numb and b.purc_seqn = i.line_seqn	")
			.where("          left outer join wrhs_mast e on e.wrhs_idcd = b.wrhs_idcd 											")
			.where("    where 1 = 1																								")
			.where("      and a.invc_date >= :invc_date21"			, arg.getParamText("invc_date1"))
			.where("      and a.invc_date <= :invc_date22"			, arg.getParamText("invc_date2"))
			.where("      and a.cstm_idcd  = :cstm_idcd2"   		, arg.getParamText("cstm_idcd"))
			.where("      and b.wrhs_idcd  = :istt_wrhs_idcd2"		, arg.getParamText("istt_wrhs_idcd"))
			.where("      and d.acct_bacd  = :acct_bacd2"     		, arg.getParamText("acct_bacd"))
			.where("      and b.item_idcd  = :item_idcd2"			, arg.getParamText("item_idcd"))
			.where("      and a.find_name like %:find_name2%"		, arg.getParameter("find_name"))
			.where("      and a.line_stat  < 2																					")
			.where(")																											")
		;
		data.param
			.where(" select a.invc_date")
			.where("      , a.cstm_idcd")
			.where("      , a.cstm_name")
			.where("      , a.item_code")
			.where("      , a.item_name")
			.where("      , a.item_spec")
			.where("      , a.qntt")
			.where("      , a.pric")
			.where("      , a.sply_amnt")
			.where("      , a.vatx_amnt")
			.where("      , a.ttsm_amnt")
			.where("      , a.invc_date as crt_date")
			.where("      , 1 as rnum")
			.where("      , a.user_memo")
			.where("      , a.trns_type")
			.where("   from cte a")
		;
		if(arg.getParamText("chk" ).contains("1")) {			//소계
			data.param
				.where(" union all")
				.where(" select null as invc_date")
				.where("      , a.cstm_idcd")
				.where("      , concat(a.cstm_name, ' 소계') as cstm_name")
				.where("      , null as item_code")
				.where("      , null as item_name")
				.where("      , null as item_spec")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , a.invc_date as crt_date")
				.where("      , 2 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by a.invc_date, a.cstm_idcd")
			;
		}
		if(arg.getParamText("chk" ).contains("2")) {			//일계
			data.param
				.where(" union all")
				.where(" select a.invc_date")
				.where("      , max(a.cstm_idcd) as cstm_idcd")
				.where("      , '일계' as cstm_name")
				.where("      , null as item_code")
				.where("      , null as item_name")
				.where("      , null as item_spec")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , a.invc_date as crt_date")
				.where("      , 3 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by a.invc_date")
			;
		}
		if(arg.getParamText("chk" ).contains("3")) {			//월계
			data.param
				.where(" union all")
				.where(" select substr(a.invc_date,1,6) as invc_date")
				.where("      , max(a.cstm_idcd) as cstm_idcd")
				.where("      , '월계' as cstm_name")
				.where("      , null as item_code")
				.where("      , null as item_name")
				.where("      , null as item_spec")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , concat(substr(a.invc_date,1,6),'99') as crt_date")
				.where("      , 4 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by concat(substr(a.invc_date,1,6), '99')")
			;
		}
		if(arg.getParamText("chk" ).contains("4")) {			//합계
			data.param
				.where(" union all")
				.where(" select null as invc_date")
				.where("      , max(a.cstm_idcd) as cstm_idcd")
				.where("      , '합계' as cstm_name")
				.where("      , null as item_code")
				.where("      , null as item_name")
				.where("      , null as item_spec")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , '99999999' as crt_date")
				.where("      , 5 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by '99999999'")
			;
		}
		data.param
			.where("     ) x ")
			.where(" order by x.crt_date, x.cstm_idcd, x.rnum ")
		;

		return  data.selectForMap();
	}

	public SqlResultMap getSearch2(HttpRequestArgument arg, int page, int rows, String sort ) throws Exception {
		DataMessage data = arg.newStorage("POS");

		data.param // 집계문  입력
			.total(" select  count(1) as maxsize	")
		;
		data.param
	    .query("select x.*																									")
	    ;
		data.param
			.where("from (																										")
			.where("with cte as (																								")
			.where("   select a.invc_numb 																						")
			.where("   	    , case when json_value(b.json_data, '$.trns_date') is null then a.invc_date else json_value(b.json_data, '$.trns_date') end as invc_date")
			.where("        , a.cstm_idcd, c.cstm_name																			")
			.where("        , b.line_seqn, b.item_idcd, d.item_code, d.item_name, d.item_spec									")
			.where("        , b.istt_qntt as qntt, b.istt_pric as pric															")
			.where("        , b.istt_amnt as sply_amnt, b.istt_vatx as vatx_amnt, b.ttsm_amnt									")
			.where("        , a.istt_wrhs_idcd	,e.wrhs_name																	")
			.where("        , i.user_memo																						")
			.where("        , case when json_value(b.json_data, '$.trns_date') is null then 1  else 2 end trns_type				")
			.where("     from purc_istt_mast a																					")
			.where("          left outer join purc_istt_item b on b.invc_numb = a.invc_numb										")
			.where("          left outer join cstm_mast c on c.cstm_idcd = a.cstm_idcd											")
			.where("          left outer join item_mast d on d.item_idcd = b.item_idcd 											")
			.where("          left outer join wrhs_mast e on e.wrhs_idcd = a.istt_wrhs_idcd 									")
			.where("          left outer join  purc_ordr_item i on b.orig_invc_numb = i.invc_numb and b.orig_seqn = i.line_seqn	")
			.where("    where 1 = 1																								")
			.where("      and ((json_value(b.json_data, '$.trns_date') is null ")
			.where("      and a.invc_date >= :invc_date11" 			, arg.getParamText("invc_date1"))
			.where("      and a.invc_date <= :invc_date12)"			, arg.getParamText("invc_date2"))
			.where("       or  (json_value(b.json_data, '$.trns_date') is not null ")
			.where("      and json_value(b.json_data, '$.trns_date') >= :invc_date13"	, arg.getParamText("invc_date1"))
			.where("      and json_value(b.json_data, '$.trns_date') <= :invc_date14))"	, arg.getParamText("invc_date2"))
			.where("      and a.cstm_idcd  = :cstm_idcd1"    		, arg.getParamText("cstm_idcd"))
			.where("      and a.istt_wrhs_idcd  = :istt_wrhs_idcd1" , arg.getParamText("istt_wrhs_idcd"))
			.where("      and d.acct_bacd  = :acct_bacd1"     		, arg.getParamText("acct_bacd"))
			.where("      and b.item_idcd  = :item_idcd1"			, arg.getParamText("item_idcd"))
			.where("      and a.find_name like %:find_name%	"		, arg.getParameter("find_name"))
			.where("      and a.line_stat  < 2																					")
			.where("    union all																								")
			.where("   select a.invc_numb, a.invc_date, a.cstm_idcd, c.cstm_name												")
			.where("        , b.line_seqn, b.item_idcd, d.item_code, d.item_name, d.item_spec									")
			.where("        , b.rett_qntt * -1 as qntt     , b.istt_pric as pric												")
			.where("        , b.sply_amnt * -1 as sply_amnt, b.vatx_amnt * -1 as vatx_amnt, b.ttsm_amnt * -1 as ttsm_amnt		")
			.where("        , b.wrhs_idcd, e.wrhs_name																			")
			.where("        , i.user_memo																						")
			.where("        , 3 as trns_type																					")
			.where("     from purc_rett_mast a																					")
			.where("          left outer join purc_rett_item b on b.invc_numb = a.invc_numb										")
			.where("          left outer join cstm_mast c on c.cstm_idcd = a.cstm_idcd											")
			.where("          left outer join item_mast d on d.item_idcd = b.item_idcd 											")
			.where("          left outer join purc_ordr_item i on b.purc_invc_numb = i.invc_numb and b.purc_seqn = i.line_seqn	")
			.where("          left outer join wrhs_mast e on e.wrhs_idcd = b.wrhs_idcd 											")
			.where("    where 1 = 1																								")
			.where("      and a.invc_date >= :invc_date21"			, arg.getParamText("invc_date1"))
			.where("      and a.invc_date <= :invc_date22"			, arg.getParamText("invc_date2"))
			.where("      and a.cstm_idcd  = :cstm_idcd2"   		, arg.getParamText("cstm_idcd"))
			.where("      and b.wrhs_idcd  = :istt_wrhs_idcd2"		, arg.getParamText("istt_wrhs_idcd"))
			.where("      and d.acct_bacd  = :acct_bacd2"     		, arg.getParamText("acct_bacd"))
			.where("      and b.item_idcd  = :item_idcd2"			, arg.getParamText("item_idcd"))
			.where("      and a.find_name like %:find_name2%"		, arg.getParameter("find_name"))
			.where("      and a.line_stat  < 2																					")
			.where(")																											")
		;
		data.param
			.where(" select a.invc_date")
			.where("      , a.item_idcd")
			.where("      , a.item_code")
			.where("      , a.item_name")
			.where("      , a.item_spec")
			.where("      , a.cstm_name")
			.where("      , a.qntt")
			.where("      , a.pric")
			.where("      , a.sply_amnt")
			.where("      , a.vatx_amnt")
			.where("      , a.ttsm_amnt")
			.where("      , a.invc_date as crt_date")
			.where("      , 1 as rnum")
			.where("      , a.user_memo")
			.where("      , a.trns_type")
			.where("   from cte a")
		;
//		if(arg.getParamText("chk" ).contains("1")) {			//소계
//			data.param
//				.where(" union all")
//				.where(" select null as invc_date")
//				.where("      , a.item_idcd")
//				.where("      , null as item_code")
//				.where("      , '소계' as item_name")
//				.where("      , null as item_spec")
//				.where("      , null as cstm_name")
//				.where("      , sum(a.qntt) as qntt")
//				.where("      , null as pric")
//				.where("      , sum(a.sply_amnt) as sply_amnt")
//				.where("      , sum(a.vatx_amnt) as vatx_amnt")
//				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
//				.where("      , max(a.invc_date) as crt_date")
//				.where("      , 4 as rnum")
//				.where("   from cte a")
//				.where("  group by a.item_idcd")
//			;
//		}
		if(arg.getParamText("chk" ).contains("2")) {			//일계
			data.param
				.where(" union all")
				.where(" select null as invc_date")
				.where("      , a.item_idcd")
				.where("      , null as item_code")
				.where("      , concat(a.item_name,' ','일계',' ' ,'-',' ',DATE_FORMAT(a.invc_date, '%Y-%m-%d')) as cstm_name")
				.where("      , null as item_spec")
				.where("      , null as cstm_name")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , max(a.invc_date) as crt_date")
				.where("      , 2 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by a.item_idcd , a.invc_date")
			;
		}
		if(arg.getParamText("chk" ).contains("3")) {			//월계
			data.param
				.where(" union all")
				.where(" select null as invc_date")
				.where("      , a.item_idcd")
				.where("      , null as item_code")
				.where("      , '월계' as cstm_name")
				.where("      , null as item_spec")
				.where("      , null as cstm_name")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , max(a.invc_date) as crt_date")
				.where("      , 3 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by a.item_idcd, concat(substr(a.invc_date,1,6), '99')")
			;
		}
		if(arg.getParamText("chk" ).contains("4")) {			//합계
			data.param
				.where(" union all")
				.where(" select null as invc_date")
				.where("      , max(a.item_idcd) as item_idcd")
				.where("      , null as item_code")
				.where("      , '합계' as item_name")
				.where("      , null as item_spec")
				.where("      , null as cstm_name")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , '99999999' as crt_date")
				.where("      , 5 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by '99999999'")
			;
		}
		data.param
			.where("     ) x ")
			.where(" order by x.item_idcd, x.crt_date, x.rnum ")
		;

		return  data.selectForMap();
	}

	public SqlResultMap getSearch3(HttpRequestArgument arg, int page, int rows, String sort ) throws Exception {
		DataMessage data = arg.newStorage("POS");

		data.param // 집계문  입력
			.total(" select  count(1) as maxsize	")
		;
		data.param
	    .query("select x.*																										")
	    ;
		data.param
			.where("from (																										")
			.where("with cte as (																								")
			.where("   select a.invc_numb																						")
			.where("   	    , case when json_value(b.json_data, '$.trns_date') is null then a.invc_date else json_value(b.json_data, '$.trns_date') end as invc_date")
			.where("        , a.cstm_idcd, c.cstm_code, c.cstm_name																")
			.where("        , b.line_seqn, b.item_idcd, d.item_code, d.item_name, d.item_spec									")
			.where("        , b.istt_qntt as qntt, b.istt_pric as pric															")
			.where("        , b.istt_amnt as sply_amnt, b.istt_vatx as vatx_amnt, b.ttsm_amnt									")
			.where("        , a.istt_wrhs_idcd	,e.wrhs_name																	")
			.where("        , i.user_memo																						")
			.where("        , case when json_value(b.json_data, '$.trns_date') is null then 1  else 2 end trns_type				")
			.where("     from purc_istt_mast a																					")
			.where("          left outer join purc_istt_item b on b.invc_numb = a.invc_numb										")
			.where("          left outer join cstm_mast c on c.cstm_idcd = a.cstm_idcd											")
			.where("          left outer join item_mast d on d.item_idcd = b.item_idcd 											")
			.where("          left outer join wrhs_mast e on e.wrhs_idcd = a.istt_wrhs_idcd 									")
			.where("          left outer join  purc_ordr_item i on b.orig_invc_numb = i.invc_numb and b.orig_seqn = i.line_seqn	")
			.where("    where 1 = 1																								")
			.where("      and ((json_value(b.json_data, '$.trns_date') is null ")
			.where("      and a.invc_date >= :invc_date11" 			, arg.getParamText("invc_date1"))
			.where("      and a.invc_date <= :invc_date12)"			, arg.getParamText("invc_date2"))
			.where("       or  (json_value(b.json_data, '$.trns_date') is not null ")
			.where("      and json_value(b.json_data, '$.trns_date') >= :invc_date13"	, arg.getParamText("invc_date1"))
			.where("      and json_value(b.json_data, '$.trns_date') <= :invc_date14))"	, arg.getParamText("invc_date2"))
			.where("      and a.cstm_idcd  = :cstm_idcd1"    , arg.getParamText("cstm_idcd"))
			.where("      and a.istt_wrhs_idcd  = :istt_wrhs_idcd1" , arg.getParamText("istt_wrhs_idcd"))
			.where("      and d.acct_bacd  = :acct_bacd1"     		, arg.getParamText("acct_bacd"))
			.where("      and b.item_idcd  = :item_idcd1"			, arg.getParamText("item_idcd"))
			.where("      and a.find_name like %:find_name%	"		, arg.getParameter("find_name"))
			.where("      and a.line_stat  < 2																					")
			.where("    union all																								")
			.where("   select a.invc_numb, a.invc_date, a.cstm_idcd, c.cstm_code, c.cstm_name									")
			.where("        , b.line_seqn, b.item_idcd, d.item_code, d.item_name, d.item_spec									")
			.where("        , b.rett_qntt * -1 as qntt     , b.istt_pric as pric												")
			.where("        , b.sply_amnt * -1 as sply_amnt, b.vatx_amnt * -1 as vatx_amnt, b.ttsm_amnt * -1 as ttsm_amnt		")
			.where("        , b.wrhs_idcd, e.wrhs_name																			")
			.where("        , i.user_memo																						")
			.where("        , 3 as trns_type																					")
			.where("     from purc_rett_mast a																					")
			.where("          left outer join purc_rett_item b on b.invc_numb = a.invc_numb										")
			.where("          left outer join cstm_mast c on c.cstm_idcd = a.cstm_idcd											")
			.where("          left outer join item_mast d on d.item_idcd = b.item_idcd 											")
			.where("          left outer join purc_ordr_item i on b.purc_invc_numb = i.invc_numb and b.purc_seqn = i.line_seqn	")
			.where("          left outer join wrhs_mast e on e.wrhs_idcd = b.wrhs_idcd 											")
			.where("    where 1 = 1																								")
			.where("      and a.invc_date >= :invc_date21"			, arg.getParamText("invc_date1"))
			.where("      and a.invc_date <= :invc_date22"			, arg.getParamText("invc_date2"))
			.where("      and a.cstm_idcd  = :cstm_idcd2"   		, arg.getParamText("cstm_idcd"))
			.where("      and b.wrhs_idcd  = :istt_wrhs_idcd2"		, arg.getParamText("istt_wrhs_idcd"))
			.where("      and d.acct_bacd  = :acct_bacd2"     		, arg.getParamText("acct_bacd"))
			.where("      and b.item_idcd  = :item_idcd2"			, arg.getParamText("item_idcd"))
			.where("      and a.find_name like %:find_name2%"		, arg.getParameter("find_name"))
			.where("      and a.line_stat  < 2																					")
			.where(")																											")
		;
		data.param
			.where(" select a.invc_date")
			.where("      , a.item_code")
			.where("      , a.item_name")
			.where("      , a.item_spec")
			.where("      , a.cstm_idcd")
			.where("      , a.cstm_code")
			.where("      , a.cstm_name")
			.where("      , a.qntt")
			.where("      , a.pric")
			.where("      , a.sply_amnt")
			.where("      , a.vatx_amnt")
			.where("      , a.ttsm_amnt")
			.where("      , a.invc_date as crt_date")
			.where("      , 1 as rnum")
			.where("      , a.user_memo")
			.where("      , a.trns_type")
			.where("   from cte a")
		;
//		if(arg.getParamText("chk" ).contains("1")) {			//소계
//			data.param
//				.where(" union all")
//				.where(" select null as invc_date")
//				.where("      , null as item_code")
//				.where("      , null as item_name")
//				.where("      , null as item_spec")
//				.where("      , a.cstm_idcd")
//				.where("      , null as cstm_code")
//				.where("      , '소계' as cstm_name")
//				.where("      , sum(a.qntt) as qntt")
//				.where("      , null as pric")
//				.where("      , sum(a.sply_amnt) as sply_amnt")
//				.where("      , sum(a.vatx_amnt) as vatx_amnt")
//				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
//				.where("      , max(a.invc_date) as crt_date")
//				.where("      , 4 as rnum")
//				.where("   from cte a")
//				.where("  group by a.cstm_idcd")
//			;
//		}
		if(arg.getParamText("chk" ).contains("2")) {			//일계
			data.param
				.where(" union all")
				.where(" select null as invc_date")
				.where("      , null as item_code")
				.where("      , null as item_name")
				.where("      , null as item_spec")
				.where("      , a.cstm_idcd")
				.where("      , null as cstm_code")
				.where("      , concat(a.cstm_name,' ','일계',' ' ,'-',' ',DATE_FORMAT(a.invc_date, '%Y-%m-%d')) as cstm_name")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , max(a.invc_date) as crt_date")
				.where("      , 2 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by a.cstm_idcd , a.invc_date")
			;
		}
		if(arg.getParamText("chk" ).contains("3")) {			//월계
			data.param
				.where(" union all")
				.where(" select null as invc_date")
				.where("      , null as item_code")
				.where("      , null as item_name")
				.where("      , null as item_spec")
				.where("      , a.cstm_idcd")
				.where("      , null as cstm_code")
				.where("      , '월계' as cstm_name")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , max(a.invc_date) as crt_date")
				.where("      , 3 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by a.cstm_idcd , concat(substr(a.invc_date,1,6), '99')	")
			;
		}
		if(arg.getParamText("chk" ).contains("4")) {			//합계
			data.param
				.where(" union all")
				.where(" select null as invc_date")
				.where("      , null as item_code")
				.where("      , null as item_name")
				.where("      , null as item_spec")
				.where("      , max(a.cstm_idcd) as cstm_idcd")
				.where("      , null as cstm_code")
				.where("      , '합계' as cstm_name")
				.where("      , sum(a.qntt) as qntt")
				.where("      , null as pric")
				.where("      , sum(a.sply_amnt) as sply_amnt")
				.where("      , sum(a.vatx_amnt) as vatx_amnt")
				.where("      , sum(a.ttsm_amnt) as ttsm_amnt")
				.where("      , '99999999' as crt_date")
				.where("      , 5 as rnum")
				.where("      , null as user_memo")
				.where("      , null as trns_type")
				.where("   from cte a")
				.where("  group by '99999999'")
			;
		}
		data.param
			.where("     ) x ")
			.where(" order by x.cstm_idcd, x.crt_date, x.rnum ")
		;

		return  data.selectForMap();
	}

	public SqlResultMap getSearch4(HttpRequestArgument arg, int page, int rows, String sort) throws Exception {


	DataMessage data = arg.newStorage("POS");

		data.param // 조회
		.where("select ")
		.where("       case when t.cstm_idcd is null then null	")
		.where("            else case when t.istt_type is not null then t.cstm_code ")
		.where("                      else null")
		.where("                 end ")
		.where("       end cstm_code")
		.where("     , case when t.cstm_idcd is null then null	")
		.where("            else case when t.istt_type is not null then t.cstm_name ")
		.where("                      else null")
		.where("                 end ")
		.where("       end cstm_name")
		.where("     , case when t.cstm_idcd is null then 5	")
		.where("            else case when t.istt_type is not null then t.istt_type ")
		.where("                      else 4")
		.where("                 end ")
		.where("       end istt_type")
		.where("	 , t.1_month					")
		.where("	 , t.2_month					")
		.where("	 , t.3_month					")
		.where("	 , t.4_month					")
		.where("	 , t.5_month					")
		.where("	 , t.6_month					")
		.where("	 , t.7_month						")
		.where("	 , t.8_month					")
		.where("	 , t.9_month					")
		.where("	 , t.10_month					")
		.where("	 , t.11_month					")
		.where("	 , t.12_month					")
		.where("	 , t.sum						")

		.where("  from (")
		.where("       select  a.cstm_idcd, a.istt_type,  b.cstm_code , b.cstm_name")
		.where("	 , sum(a.1_month)	as 1_month					")
		.where("	 , sum(a.2_month)	as 2_month					")
		.where("	 , sum(a.3_month)	as 3_month					")
		.where("	 , sum(a.4_month)	as 4_month					")
		.where("	 , sum(a.5_month)	as 5_month					")
		.where("	 , sum(a.6_month)	as 6_month					")
		.where("	 , sum(a.7_month)	as 7_month					")
		.where("	 , sum(a.8_month)	as 8_month					")
		.where("	 , sum(a.9_month)	as 9_month					")
		.where("	 , sum(a.10_month)	as 10_month					")
		.where("	 , sum(a.11_month)	as 11_month					")
		.where("	 , sum(a.12_month)	as 12_month					")
		.where("	 , sum(a.sum) 		as sum						")
		.where("  from (											")
		.where("        select s.*, 1 as istt_type")
		.where("         from (")
		.where("		select a.cstm_idcd															")
		.where("			 , sum(if(MONTH(a.invc_date) = 1,  b.ttsm_amnt, 0)) AS 1_month			")
		.where(" 			 , sum(if(MONTH(a.invc_date) = 2,  b.ttsm_amnt, 0)) AS 2_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 3,  b.ttsm_amnt, 0)) AS 3_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 4,  b.ttsm_amnt, 0)) AS 4_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 5,  b.ttsm_amnt, 0)) AS 5_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 6,  b.ttsm_amnt, 0)) AS 6_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 7,  b.ttsm_amnt, 0)) AS 7_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 8,  b.ttsm_amnt, 0)) AS 8_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 9,  b.ttsm_amnt, 0)) AS 9_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 10, b.ttsm_amnt, 0)) AS 10_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 11, b.ttsm_amnt, 0)) AS 11_month			")
		.where("			 , sum(if(MONTH(a.invc_date) = 12, b.ttsm_amnt, 0)) AS 12_month			")
		.where("			 , sum(b.ttsm_amnt) 								AS sum				")
		.where("      from purc_istt_mast a                                                 		")
		.where("             left outer join purc_istt_item b on b.invc_numb = a.invc_numb  		")
//		.where("             left outer join acpt_mast c on c.invc_numb = b.acpt_numb       		")
		.where("    where 1 = 1                                                             		")
		.where("       and a.line_stat < 2                                                  		")
//		.where("       and ((c.acpt_dvcd = '1000' and json_value(c.json_data, '$.prod_trst_dvcd') <> '2000') or (c.acpt_dvcd = '2000' and json_value(c.json_data, '$.prod_trst_dvcd') <> '3000')) ")
		.where("       and substr(a.invc_date, 1, 4) = substr(:invc_date1 , 1, 4)" , arg.getParamText("invc_date")	 )
		.where("       and json_value(b.json_data, '$.trns_date') is null                          	")
		.where("    group by a.cstm_idcd                                                           	")
		.where("                                                                                   	")
		.where("   ) s")
		.where("  where 1 = 1")
		.where("  and s.sum is not null	"	)

		.where("    union all                                                                      	")
		.where("                                                                                   	")
		.where("        select s.*, 1 as istt_type")
		.where("         from (")
		.where("   select a.cstm_idcd                                                              	")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 1,   b.ttsm_amnt, 0)) AS 1_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 2,   b.ttsm_amnt, 0)) AS 2_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 3,   b.ttsm_amnt, 0)) AS 3_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 4,   b.ttsm_amnt, 0)) AS 4_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 5,   b.ttsm_amnt, 0)) AS 5_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 6,   b.ttsm_amnt, 0)) AS 6_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 7,   b.ttsm_amnt, 0)) AS 7_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 8,   b.ttsm_amnt, 0)) AS 8_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 9,   b.ttsm_amnt, 0)) AS 9_month     ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 10,  b.ttsm_amnt, 0)) AS 10_month    ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 11,  b.ttsm_amnt, 0)) AS 11_month    ")
		.where("          , sum(if(MONTH( json_value(b.json_data, '$.trns_date')) = 12,  b.ttsm_amnt, 0)) AS 12_month    ")
		.where("          , sum(b.ttsm_amnt) 															  AS sum		 ")
		.where("      from purc_istt_mast a                                                                              ")
		.where("             left outer join purc_istt_item b on b.invc_numb = a.invc_numb                               ")
//		.where("             left outer join acpt_mast c on c.invc_numb = b.acpt_numb                                    ")
		.where("    where 1 = 1                                                                                          ")
		.where("       and a.line_stat < 2                                                                               ")
//		.where("       and ((c.acpt_dvcd = '1000' and json_value(c.json_data, '$.prod_trst_dvcd') <> '2000') or (c.acpt_dvcd = '2000' and json_value(c.json_data, '$.prod_trst_dvcd') <> '3000')) ")
		.where("       and substr(json_value(b.json_data, '$.trns_date') , 1, 4) = substr(:invc_date2 , 1, 4)" , arg.getParamText("invc_date"))
		.where("       and json_value(b.json_data, '$.trns_date') is not null                                            ")
		.where("    group by a.cstm_idcd                                                                                 ")
		.where("                                                                                                         ")
		.where("   ) s")
		.where("  where 1 = 1")
		.where("  and s.sum is not null	"	)

		.where("    union all                                                                                            ")
		.where("                                                                                                         ")
		.where("        select s.*, 1 as isst_type")
		.where("         from (")
		.where("   select a.cstm_idcd                                                                                    ")
		.where("        , sum(if(MONTH(a.invc_date) = 1,  b.ttsm_amnt, 0)) AS 1_month                                    ")
		.where("          , sum(if(MONTH(a.invc_date) = 2,  b.ttsm_amnt, 0)) AS 2_month                                  ")
		.where("          , sum(if(MONTH(a.invc_date) = 3,  b.ttsm_amnt, 0)) AS 3_month                                  ")
		.where("          , sum(if(MONTH(a.invc_date) = 4,  b.ttsm_amnt, 0)) AS 4_month                                  ")
		.where("          , sum(if(MONTH(a.invc_date) = 5,  b.ttsm_amnt, 0)) AS 5_month                                  ")
		.where("          , sum(if(MONTH(a.invc_date) = 6,  b.ttsm_amnt, 0)) AS 6_month                                  ")
		.where("          , sum(if(MONTH(a.invc_date) = 7,  b.ttsm_amnt, 0)) AS 7_month                                  ")
		.where("          , sum(if(MONTH(a.invc_date) = 8,  b.ttsm_amnt, 0)) AS 8_month                                  ")
		.where("          , sum(if(MONTH(a.invc_date) = 9,  b.ttsm_amnt, 0)) AS 9_month                                  ")
		.where("          , sum(if(MONTH(a.invc_date) = 10, b.ttsm_amnt, 0)) AS 10_month                                 ")
		.where("          , sum(if(MONTH(a.invc_date) = 11, b.ttsm_amnt, 0)) AS 11_month                                 ")
		.where("          , sum(if(MONTH(a.invc_date) = 12, b.ttsm_amnt, 0)) AS 12_month                                 ")
		.where("          , sum(b.ttsm_amnt) 								 AS sum                                      ")
		.where("     from purc_rett_mast a                                                                               ")
		.where("           left outer join purc_rett_item b on b.invc_numb = a.invc_numb                                 ")
//		.where("             left outer join acpt_mast c  on c.invc_numb = b.acpt_numb                                   ")
		.where("    where 1 = 1                                                                                          ")
		.where("       and a.line_stat < 2                                                                               ")
//		.where("       and ((c.acpt_dvcd = '1000' and json_value(c.json_data, '$.prod_trst_dvcd') <> '2000') or (c.acpt_dvcd = '2000' and json_value(c.json_data, '$.prod_trst_dvcd') <> '3000')) ")
		.where("       and substr(a.invc_date , 1, 4) = substr(:invc_date3 , 1, 4)" , arg.getParamText("invc_date"))
		.where("   ) s")
		.where("  where 1 = 1")
		.where("  and s.sum is not null	"	)
		.where(") a                                                                                                       ")
		.where("  left outer join cstm_mast b on b.cstm_idcd = a.cstm_idcd                                                ")
		.where("where 1 = 1                                                                                               ")
		.where("group by a.cstm_idcd, a.istt_type with rollup                                                             ")
		.where(") t")
		;

		if (page == 0 && rows == 0) {
			return data.selectForMap(sort);
		} else {
			return data.selectForMap(page, rows, (page==1),sort);
		}
	}
}
