Ext.define('module.custom.kitec.prod.prodplan.model.ProdPlan',{ extend:'Axt.data.Model',
	fields  : [
		{	name: 'seqn',			type: 'float'
		},{	name: 'cvic',			type: 'string'
		},{	name: 'line_seqn',		type: 'string'
		},{	name: 'cvic_idcd',		type: 'string'
		},{	name: 'num',			type: 'string'
		},{	name: 'dvcd',			type: 'string'
		},{	name: 'day1',			type: 'string'
		},{	name: 'day2',			type: 'string'
		},{	name: 'day3',			type: 'string'
		},{	name: 'day4',			type: 'string'
		},{	name: 'day5',			type: 'string'
		},{	name: 'day6',			type: 'string'
		},{	name: 'day7',			type: 'string'
		},{	name: 'day8',			type: 'string'
		},{	name: 'day9',			type: 'string'
		},{	name: 'day10',			type: 'string'
		},{	name: 'day11',			type: 'string'
		},{	name: 'day12',			type: 'string'
		},{	name: 'day13',			type: 'string'
		},{	name: 'day14',			type: 'string'
		},{	name: 'day15',			type: 'string'
		},{	name: 'day16',			type: 'string'
		},{	name: 'day17',			type: 'string'
		},{	name: 'day18',			type: 'string'
		},{	name: 'day19',			type: 'string'
		},{	name: 'day20',			type: 'string'
		},{	name: 'day21',			type: 'string'
		},{	name: 'day22',			type: 'string'
		},{	name: 'day23',			type: 'string'
		},{	name: 'day24',			type: 'string'
		},{	name: 'day25',			type: 'string'
		},{	name: 'day26',			type: 'string'
		},{	name: 'day27',			type: 'string'
		},{	name: 'day28',			type: 'string'
		},{	name: 'day29',			type: 'string'
		},{	name: 'day30',			type: 'string'
		},{	name: 'day31',			type: 'string'

		},{	name : 'bzpl_idcd'		, type : 'string', defaultValue : _global.stor_id		//사업장ID
		}
	]
});
