insert into sscd_mast (
            SSCD_IDCD
           ,LANG_DVCD
           ,SITE_IDCD
           ,SSCD_CODE
           ,SSCD_NAME
           ,SSCD_DVCD
           ,DFLT_VALU
           ,LKUP_VALU
           ,SBSC_VALU
           ,USER_MEMO
           ,SYSM_MEMO
           ,PRNT_IDCD
           ,LINE_LEVL
           ,LINE_ORDR
           ,LINE_STAT
           ,LINE_CLOS
           ,FIND_NAME
           ,UPDT_USER_NAME
           ,UPDT_IPAD
           ,UPDT_DTTM
           ,UPDT_IDCD
           ,UPDT_URIF
           ,CRTE_USER_NAME
           ,CRTE_IPAD
           ,CRTE_DTTM
           ,CRTE_IDCD
           ,CRTE_URIF
)
select 
            CODE_ID
           ,LANG_GBCD
           ,SITE_ID
           ,CODE_CD
           ,CODE_NM
           ,CODE_GB
           ,DEFLT_VAL
           ,LOOKUP_VAL
           ,ITM_VAL
           ,USR_MEMO
           ,SYS_MEMO
           ,PRNT_ID
           ,ROW_LVL
           ,ROW_ORD
           ,ROW_STS
           ,ROW_CLOS
           ,FIND_NM
           ,UPT_USR_NM
           ,UPT_IP
           ,UPT_DTTM
           ,UPT_ID
           ,UPT_UI
           ,CRT_USR_NM
           ,CRT_IP
           ,CRT_DTTM
           ,CRT_ID
           ,CRT_UI
from code_mst

